# Generated by Django 4.1.4 on 2022-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraping", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "City", "verbose_name_plural": "Cities"},
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
